site_name: Jérémy Wiki
site_description: "Tous les trucs & astuces de Jerem"
site_author: "Jérémy DELGADO"

repo_url: https://github.com/PixiBixi/pixibixi.github.io
remote_branch: docs

theme:
  features:
    - header.autohide
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
  name: material
  language: fr

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
  - search:
      lang: fr
  - tags
  - search

extra:
  analytics:
    provider: google
    property: G-NHG8VK60NB
