site_name: Jérémy Wiki
site_description: "Tous les trucs & astuces de Jerem"
site_author: "Jérémy DELGADO"

repo_url: https://github.com/PixiBixi/pixibixi.github.io
remote_branch: docs

theme:
  features:
    - toc.integrate
    - header.autohide
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
  name: material
  language: fr

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
  - search:
      lang: fr
  - tags
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

extra:
  generator: false
  analytics:
    provider: google
    property: G-NHG8VK60NB
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Pixel__Art

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
